name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint, Test & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-pnpm-env

      - name: Check code formatting (Biome)
        run: pnpm format:ci

      - name: Lint code (ESLint)
        run: pnpm lint

      - name: Run tests (Vitest)
        run: pnpm test
